global:
  environment: test

namespaceOverride: hms-test

frontend:
  replicaCount: 1
  image:
    tag: latest-test

backend:
  replicaCount: 1
  image:
    tag: latest-test
  config:
    databaseUrl: file:/app/data/sims-test.db
    corsOrigin: https://test.kansalt.com
  persistence:
    data:
      size: 3Gi
    uploads:
      size: 6Gi
    logs:
      size: 2Gi

ingress:
  hosts:
    - host: test.kansalt.com
      frontendPaths:
        - path: /
          pathType: Prefix
      backendPaths:
        - path: /api
          pathType: Prefix
        - path: /uploads
          pathType: Prefix
  tls: []
