global:
  environment: dev

namespaceOverride: hms-dev

frontend:
  replicaCount: 1
  image:
    tag: latest-dev

backend:
  replicaCount: 1
  image:
    tag: latest-dev
  config:
    databaseUrl: file:/app/data/sims-dev.db
    corsOrigin: https://kansalt.dev.com
  persistence:
    data:
      size: 2Gi
    uploads:
      size: 5Gi
    logs:
      size: 1Gi

ingress:
  hosts:
    - host: kansalt.dev.com
      frontendPaths:
        - path: /sims
          pathType: Prefix
      backendPaths:
        - path: /sims/api
          pathType: Prefix
        - path: /sims/uploads
          pathType: Prefix
  tls: []
